# Generated by Django 3.2.15 on 2022-10-31 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50)),
                ("risk_factor", models.PositiveSmallIntegerField()),
                ("amount_from", models.PositiveIntegerField()),
                ("amount_to", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BotRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("money", models.PositiveIntegerField()),
                ("days", models.PositiveIntegerField()),
                ("money_left", models.PositiveIntegerField()),
                ("investment_returned", models.FloatField()),
                ("return_percent", models.FloatField()),
                ("buy_coords", models.TextField()),
                ("sell_coords", models.TextField()),
                ("plot_coords", models.TextField()),
                ("redeemed", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stats.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
